### ISSUE TITLE
[PE-D][Tester C] Truncation of money added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T13-1/tp#124]
When adding money into an account, it would be nice if the user was explicitly warned that only values after the second decimal place is dropped.

Maybe consider adding a warning that there is some leftover value that is dropped:

```
add SGD 10.001
--------------------------------------------------
You have successfully added SGD 10.00 into your account
{ Warning here }

```

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ltzehan/ped#1

**Comment by Bawfen** [comment]
Should include in this in the user guide

**Comment by Gan868611** [comment]
we should check the against the input to make sure only max 2dp is inserted
