### ISSUE TITLE
[PE-D][Tester A] Wrong exception description

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-1/tp#126]
![Screenshot 2023-03-31 164407.png](https://raw.githubusercontent.com/avielcx/ped/main/files/8da40890-39ba-4900-aeda-3b061d6de731.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: avielcx/ped#5

**Comment by Gan868611** [comment]
Not sure about this, i think this exception is raised because there is not 13th month in standard date format

**Comment by Bawfen** [comment]
We will write that only valid dates are allowed in the UG.
