### ISSUE TITLE
[PE-D][Tester A] cannot detect a number if there are commas

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-1/tp#143]
![image.png](https://raw.githubusercontent.com/avielcx/ped/main/files/9876ff91-743c-4a4d-a2d9-78ee12004c1a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: avielcx/ped#12

**Comment by Bawfen** [comment]
Shall we just include the constraint that only numerical inputs are allowed in the UG?

**Comment by Gan868611** [comment]
I think can.

**Comment by Bawfen** [comment]
Ok we shall add it to the UG

**Comment by Gan868611** [comment]
Updated in lastest UG
