### ISSUE TITLE
[PE-D][Tester A] does not detect wrong input as per image

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-1/tp#145]
![image.png](https://raw.githubusercontent.com/avielcx/ped/main/files/22465e20-18f7-4cb1-89ba-a1e2229d6812.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: avielcx/ped#13

**Comment by Bawfen** [comment]
Linked to #164
