### ISSUE TITLE
[PE-D][Tester A] wrong exception description

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-1/tp#153]
![image.png](https://raw.githubusercontent.com/avielcx/ped/main/files/c53bb56f-8afe-40cf-9b96-96e69f730514.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: avielcx/ped#17

**Comment by woowenjun99** [comment]
```
add SGD 1000000000000000000000000
```
will lead to an error, investigating now.
