### ISSUE TITLE
[PE-D][Tester E] Error in calculation - follow up

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T13-1/tp#174]
![Picture3.png](https://raw.githubusercontent.com/raydent30/ped/main/files/1701bfdf-c158-437d-b941-4fc8ffdc9b10.png)

Unable to withdraw the supposed balance

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: raydent30/ped#5

**Comment by Bawfen** [comment]
Need to implement a check for at max 2 decimal places,  maybe by inspecting the substring after the decimal place? Also should include this in the user guide

**Comment by Gan868611** [comment]
ya, add, withdraw and exchange all need to limit for 2dp
