### ISSUE TITLE
[PE-D][Tester D] Slight inaccuracies in exchange rate

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-1/tp#175]
![image.png](https://raw.githubusercontent.com/moseslee9012/ped/main/files/bae88ed2-4219-4f2b-9471-57bc2930bd26.png)

After a certain threshold, the exchange rate is not very accurate, could have an error or warning message to users about the maximum amount that can be calculated, such as "The amount is too large, please enter an amount lower than X for better accuracy"

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: moseslee9012/ped#6

**Comment by Bawfen** [comment]
Should include a line in the UG and also implement a limit in code for the show-rate command
