### ISSUE TITLE
[PE-D][Tester B] User guide does not show the output for correct command for `exchange`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T13-1/tp#176]
![image.png](https://raw.githubusercontent.com/jaredoong/ped/main/files/c7106cbb-d76d-4446-9d61-fc7292b88df5.png)

The comments on what the command means is rather misleading and may be mistaken for the expected output. You could consider explaining the command on a separate line, and instead show the expected output when a correct command is given.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jaredoong/ped#9

**Comment by Bawfen** [comment]
Need to amend the UG with the correct output and move the comments out
