### ISSUE TITLE
Ui Class

### ISSUE THREAD

**Issue by Bawfen** [AY2223S2-CS2113-T13-1/tp#22]
Also includes the Enum of Messages

**Comment by woowenjun99** [comment]
1. Do you want me to implement more specific functions such as `printHelp()` or would you like me to implement a generic function such as `printMessage(String message)` as discussed in our meeting and when being called, pass in the parameter?
```java
// General Function
printMessage(Message.HELP.getMessage());

// Specific Function
printHelp();
```
2. Do you want to implement a `printf` function that takes in the format and varargs as I noticed it was not mentioned in the discussion.

3. What is `printSpacer`?

4. How many dashes would you like for `printIndent`?

5. Would you like to read in the commands one-by-one or a string as a whole
