### ISSUE TITLE
Misleading error message when create-account with amount

### ISSUE THREAD

**Issue by woowenjun99** [AY2223S2-CS2113-T13-1/tp#46]
```
>>> create-account SGD 200
>>> Please check that you have correctly provided the currency of the account to add
```
Expected: The currency is valid. As a user, I am confused what this error message means. Maybe a clearer message can be shown.

**Comment by Bawfen** [comment]
According to the user guide, create-account does not allow for the setting of amount and thus the user input contains too many arguments. That is why it is throwing the error.

Agree we should consider rewording it.
