### ISSUE TITLE
Trying to add many "9"s showed a message that should not have been shown

### ISSUE THREAD

**Issue by woowenjun99** [AY2223S2-CS2113-T13-1/tp#60]
<img width="867" alt="Screenshot 2023-03-15 at 6 37 24 PM" src="https://user-images.githubusercontent.com/88195289/225284177-0dcf1368-8960-4180-a2cf-00d8b57a9e1d.png">

**Comment by Gan868611** [comment]
I found that the breakpoint is between 9,999,999 and 10,000,000

**Comment by Gan868611** [comment]
![image](https://user-images.githubusercontent.com/56477330/225301526-945bb963-7e35-4a56-8e2e-702f7afd6039.png)
i found out that it is something about the max size of `int`.
